kubectl delete namespace accounting
kubectl delete namespace accounts-receivable
kubectl delete namespace client-onboarding
kubectl delete namespace credit-initiation
kubectl delete namespace currency-exchange
kubectl delete namespace distribution
kubectl delete namespace finance
kubectl delete namespace fraud-detection
kubectl delete namespace human-capital
kubectl delete namespace logistics
kubectl delete namespace manufacturing
kubectl delete namespace mastercard-processor
kubectl delete namespace plant-maintenance
kubectl delete namespace production-planning
kubectl delete namespace sales
kubectl delete namespace visa-processor